package subgoal;

/**
 * *************************************************************
 *
 * Subgoal Data Preparation Written by Dr. Andrew Kwok-Fai LUI On 28/2/2020
 *
 * Copyright Andrew Kwok-Fai LUI 2020
 *
 */
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

public class ExampleEditor extends javax.swing.JPanel {

    private Example currentExample = null;
    private ExampleEditorListener listener = null;

    public ExampleEditor() {
        initComponents();
        setExampleEditorEnabled(false);
    }

    public void setListener(ExampleEditorListener listener) {
        this.listener = listener;
    }

    public void setExample(Example example) {
        currentExample = example;
        refreshExampleInfoJPanel(currentExample);
    }

    public Example newExample(String id) {
        currentExample = new Example(id);
        currentExample.put("Title", "");
        currentExample.put("Keywords", "");
        currentExample.put("Desc", "");
        currentExample.put("Labels", new ArrayList());
        currentExample.put("Program", "");
        refreshExampleInfoJPanel(currentExample);
        return currentExample;
    }

    void setExampleEditorEnabled(boolean enabled) {
        jTextField1.setEnabled(enabled);
        jTextField2.setEnabled(enabled);
        jTextField3.setEnabled(enabled);
        jTextArea1.setEnabled(enabled);
        jTextArea2.setEnabled(enabled);
        labelEditor2.setEnabled(enabled);
    }

    public void copyToExampleMap(HashMap exampleMap) {
        exampleMap.put("ID", jTextField1.getText());
        exampleMap.put("Title", jTextField2.getText());
        exampleMap.put("Keywords", jTextField3.getText());
        exampleMap.put("Desc", jTextArea2.getText());
        exampleMap.put("Program", jTextArea1.getText());
    }

    public void refreshExampleInfoJPanel(HashMap exampleMap) {
        if (exampleMap == null) {
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextArea1.setText("");
            jTextArea2.setText("");
            labelEditor2.setLabelList(new ArrayList());
            setExampleEditorEnabled(false);
            return;
        }
        jTextField1.setText((String) exampleMap.getOrDefault("ID", ""));
        jTextField2.setText((String) exampleMap.getOrDefault("Title", ""));
        jTextField3.setText((String) exampleMap.getOrDefault("Keywords", ""));
        jTextArea1.setText((String) exampleMap.getOrDefault("Program", ""));
        jTextArea2.setText((String) exampleMap.getOrDefault("Desc", ""));
        labelEditor2.setLabelList((List) exampleMap.getOrDefault("Labels", new ArrayList()));
        setExampleEditorEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        labelEditor2 = new subgoal.LabelEditor();

        setLayout(new java.awt.GridBagLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Program Code"));
        jPanel3.setPreferredSize(new java.awt.Dimension(480, 800));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jTextArea1.setBackground(new java.awt.Color(255, 255, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextArea1CaretUpdate(evt);
            }
        });
        jTextArea1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextArea2FocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        jPanel3.add(jScrollPane1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jPanel3, gridBagConstraints);

        jPanel4.setPreferredSize(new java.awt.Dimension(360, 800));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jTextField1.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jTextField1.setActionCommand("");
        jTextField1.setBorder(javax.swing.BorderFactory.createTitledBorder("ID"));
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextArea2FocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel4.add(jTextField1, gridBagConstraints);

        jTextField2.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jTextField2.setActionCommand("");
        jTextField2.setBorder(javax.swing.BorderFactory.createTitledBorder("Title"));
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextArea2FocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel4.add(jTextField2, gridBagConstraints);

        jTextField3.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jTextField3.setActionCommand("");
        jTextField3.setBorder(javax.swing.BorderFactory.createTitledBorder("Keywords"));
        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextArea2FocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel4.add(jTextField3, gridBagConstraints);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Description"));

        jTextArea2.setColumns(20);
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextArea2FocusLost(evt);
            }
        });
        jScrollPane2.setViewportView(jTextArea2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        jPanel4.add(jScrollPane2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        jPanel4.add(labelEditor2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        add(jPanel4, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextArea2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextArea2FocusLost
        if (currentExample == null) {
            return;
        }
        copyToExampleMap(currentExample);
        if (listener != null) {
            String whichComp = null;
            Object source = evt.getSource();
            if (source == jTextField1) {
                whichComp = "ID";
            } else if (source == jTextField2) {
                whichComp = "Title";
            } else if (source == jTextField3) {
                whichComp = "Keywords";
            } else if (source == jTextArea1) {
                whichComp = "Program";
            } else if (source == jTextArea2) {
                whichComp = "Desc";
            }
            listener.valueChanged(currentExample, whichComp);
        }
    }//GEN-LAST:event_jTextArea2FocusLost

    private void jTextArea1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextArea1CaretUpdate
        SelectRangeFinder finder = new SelectRangeFinder(jTextArea1.getText(), jTextArea1.getSelectionStart(),
                jTextArea1.getSelectionEnd());
        if (!finder.isValid()) {
            return;
        }
        // IMPORTANT: must store the value first because setRowRange will change the status
        boolean toChangeRow = labelEditor2.isMarkingRow();
        boolean toChangeCol = labelEditor2.isMarkingColumn();

        if (toChangeRow) {
            labelEditor2.setRowRange(finder.getStartrow() + "-" + finder.getEndrow());
        }
        if (toChangeCol) {
            if (finder.isSameRow()) {
                labelEditor2.setColRange(finder.getStartcol() + "-" + finder.getEndcol());
            } else {
                labelEditor2.setColRange("");
            }
        }

    }//GEN-LAST:event_jTextArea1CaretUpdate


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private subgoal.LabelEditor labelEditor2;
    // End of variables declaration//GEN-END:variables
}
